<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <OutputPath>..\..\bin\$(Configuration)\Widgets\Clock\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Fonts\DroidSans.ttf" />
    <Resource Include="Fonts\DroidSansMono.ttf" />
    <Resource Include="Resources\Weather\cloud_1.png" />
    <Resource Include="Resources\Weather\cloud_2.png" />
    <Resource Include="Resources\Weather\cloud_3.png" />
    <Resource Include="Resources\Weather\cloud_4.png" />
    <Resource Include="Resources\Weather\cloud_5.png" />
    <Resource Include="Resources\Weather\cloud_6.png" />
    <Resource Include="Resources\Weather\cloud_7.png" />
    <Resource Include="Resources\Weather\cloud_8.png" />
    <Resource Include="Resources\Weather\flare.png" />
    <Resource Include="Resources\Weather\humidity_lvl1.png" />
    <Resource Include="Resources\Weather\humidity_lvl2.png" />
    <Resource Include="Resources\Weather\humidity_lvl3.png" />
    <Resource Include="Resources\Weather\humidity_lvl4.png" />
    <Resource Include="Resources\Weather\layer_drop1.png" />
    <Resource Include="Resources\Weather\layer_drop2.png" />
    <Resource Include="Resources\Weather\layer_drop3.png" />
    <Resource Include="Resources\Weather\layer_drop4.png" />
    <Resource Include="Resources\Weather\layer_drop5.png" />
    <Resource Include="Resources\Weather\layer_drop6.png" />
    <Resource Include="Resources\Weather\layer_drop7.png" />
    <Resource Include="Resources\Weather\lightning_01.png" />
    <Resource Include="Resources\Weather\lightning_02.png" />
    <Resource Include="Resources\Weather\lightning_03.png" />
    <Resource Include="Resources\Weather\raindrop_streaks.png" />
    <Resource Include="Resources\Weather\rain_fall.png" />
    <Resource Include="Resources\Weather\rain_wiper.png" />
    <Resource Include="Resources\Weather\snowflake1.png" />
    <Resource Include="Resources\Weather\snowflake2.png" />
    <Resource Include="Resources\Weather\snowflake3.png" />
    <Resource Include="Resources\Weather\snowflake4.png" />
    <Resource Include="Resources\Weather\snowflake5.png" />
    <Resource Include="Resources\Weather\sun.png" />
    <Resource Include="Resources\Weather\weather_1.png" />
    <Resource Include="Resources\Weather\weather_11.png" />
    <Resource Include="Resources\Weather\weather_12.png" />
    <Resource Include="Resources\Weather\weather_13.png" />
    <Resource Include="Resources\Weather\weather_14.png" />
    <Resource Include="Resources\Weather\weather_15.png" />
    <Resource Include="Resources\Weather\weather_16.png" />
    <Resource Include="Resources\Weather\weather_17.png" />
    <Resource Include="Resources\Weather\weather_18.png" />
    <Resource Include="Resources\Weather\weather_19.png" />
    <Resource Include="Resources\Weather\weather_2.png" />
    <Resource Include="Resources\Weather\weather_20.png" />
    <Resource Include="Resources\Weather\weather_21.png" />
    <Resource Include="Resources\Weather\weather_22.png" />
    <Resource Include="Resources\Weather\weather_23.png" />
    <Resource Include="Resources\Weather\weather_24.png" />
    <Resource Include="Resources\Weather\weather_25.png" />
    <Resource Include="Resources\Weather\weather_26.png" />
    <Resource Include="Resources\Weather\weather_29.png" />
    <Resource Include="Resources\Weather\weather_3.png" />
    <Resource Include="Resources\Weather\weather_30.png" />
    <Resource Include="Resources\Weather\weather_31.png" />
    <Resource Include="Resources\Weather\weather_32.png" />
    <Resource Include="Resources\Weather\weather_33.png" />
    <Resource Include="Resources\Weather\weather_34.png" />
    <Resource Include="Resources\Weather\weather_35.png" />
    <Resource Include="Resources\Weather\weather_36.png" />
    <Resource Include="Resources\Weather\weather_37.png" />
    <Resource Include="Resources\Weather\weather_38.png" />
    <Resource Include="Resources\Weather\weather_39.png" />
    <Resource Include="Resources\Weather\weather_4.png" />
    <Resource Include="Resources\Weather\weather_40.png" />
    <Resource Include="Resources\Weather\weather_41.png" />
    <Resource Include="Resources\Weather\weather_42.png" />
    <Resource Include="Resources\Weather\weather_43.png" />
    <Resource Include="Resources\Weather\weather_44.png" />
    <Resource Include="Resources\Weather\weather_5.png" />
    <Resource Include="Resources\Weather\weather_51.png" />
    <Resource Include="Resources\Weather\weather_52.png" />
    <Resource Include="Resources\Weather\weather_53.png" />
    <Resource Include="Resources\Weather\weather_54.png" />
    <Resource Include="Resources\Weather\weather_6.png" />
    <Resource Include="Resources\Weather\weather_7.png" />
    <Resource Include="Resources\Weather\weather_8.png" />
    <Resource Include="Resources\Weather\wind_lvl1.png" />
    <Resource Include="Resources\Weather\wind_lvl2.png" />
    <Resource Include="Resources\Weather\wind_lvl3.png" />
    <Resource Include="Resources\Weather\wind_lvl4.png" />
    <None Update="NLog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="widget.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\FlipClock\Background\flip_bg.png" />
    <Resource Include="Resources\FlipClock\Background\flip_clock_tab_down.png" />
    <Resource Include="Resources\FlipClock\Background\flip_clock_tab_shadow.png" />
    <Resource Include="Resources\FlipClock\Background\flip_clock_tab_up.png" />
    <Resource Include="Resources\FlipClock\Digits\0.png" />
    <Resource Include="Resources\FlipClock\Digits\1.png" />
    <Resource Include="Resources\FlipClock\Digits\2.png" />
    <Resource Include="Resources\FlipClock\Digits\3.png" />
    <Resource Include="Resources\FlipClock\Digits\4.png" />
    <Resource Include="Resources\FlipClock\Digits\5.png" />
    <Resource Include="Resources\FlipClock\Digits\6.png" />
    <Resource Include="Resources\FlipClock\Digits\7.png" />
    <Resource Include="Resources\FlipClock\Digits\8.png" />
    <Resource Include="Resources\FlipClock\Digits\9.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\FlipClock\am.png" />
    <Resource Include="Resources\FlipClock\pm.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\FlipClock\Background\flip_clock_divider.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\FlipClock\base_default.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="clock_icon.ico" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\FlipClock\SearchIcon.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\FlipClock\SearchCancelIcon.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\analogclockbig_preview.png" />
    <Resource Include="Resources\flipclock_preview.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\AnalogClockBig\clock_base_day.png" />
    <Resource Include="Resources\AnalogClockBig\clock_center_dot.png" />
    <Resource Include="Resources\AnalogClockBig\clock_hour.png" />
    <Resource Include="Resources\AnalogClockBig\clock_minute.png" />
    <Resource Include="Resources\AnalogClockBig\clock_second.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\AnalogClockBig\clock_base_night.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\analogclocksmall_preview.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\AnalogClockSmall\clock_base_night.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\AnalogClockSmall\clock_center_dot.png" />
    <Resource Include="Resources\AnalogClockSmall\clock_base_day.png" />
    <Resource Include="Resources\AnalogClockSmall\clock_hour.png" />
    <Resource Include="Resources\AnalogClockSmall\clock_minute.png" />
    <Resource Include="Resources\AnalogClockSmall\clock_second.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\logo.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\dualclock_preview.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\DualClock\clock_center_dot.png" />
    <Resource Include="Resources\DualClock\clock_base_day.png" />
    <Resource Include="Resources\DualClock\clock_hour.png" />
    <Resource Include="Resources\DualClock\clock_minute.png" />
    <Resource Include="Resources\DualClock\clock_base_night.png" />
    <Resource Include="Resources\DualClock\clock_second.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\DualClock\clock_bg.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\FlipClock\modern_base_default.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\FlipClock\modern_forecast_base.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\modernsense_preview.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\FlipClock\wide_base_default.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\FlipClock\wide_forecast_base.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\wideflipclock_preview.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Resources\flipclocknoweather_preview.png" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Controls\Sense4FlipTab.xaml.cs" />
    <Compile Remove="Windows\Sense4FlipClock.xaml.cs" />
    <Page Remove="Controls\Sense4FlipTab.xaml" />
    <Page Remove="Windows\Sense4FlipClock.xaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NLog" Version="4.7.9" />
  </ItemGroup>
  <ItemGroup>
    <Page Remove="Skins\**\*.xaml" />
    <Content Include="Skins\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="App.cs" />
    <Compile Remove="Settings.cs" />
    <Compile Remove="App.cs" />
    <Compile Remove="Settings.cs" />
    <Compile Remove="Domain\WeatherProviderManager.cs" />
    <Compile Remove="Controls\ModernForecastItem.xaml.cs" />
    <Compile Remove="Controls\ForecastItem.xaml.cs" />
    <Compile Remove="Controls\WideForecastItem.xaml.cs" />
    <Compile Remove="Windows\**" />
    <Page Remove="Windows\**" />
    <Page Remove="Controls\ModernForecastItem.xaml" />
    <Page Remove="Controls\ForecastItem.xaml" />
    <Page Remove="Controls\WideForecastItem.xaml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Home.Base\Home.Base.csproj">
      <Private>false</Private>
    </ProjectReference>

    <ProjectReference Include="..\..\Weather.Base\Weather.Base.csproj">
      <Private>true</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
