<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <Copyright>© Stealth 2021</Copyright>
    <Authors>Stealth</Authors>
    <Version>1.0.4</Version>    
  <OutputPath>..\..\..\bin\$(Configuration)\Extras\Weather\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Home.Base\Home.Base.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\..\Weather.Base\Weather.Base.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
  <ItemGroup>
    <Content Include="wc.ext.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
