<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <OutputPath>..\bin\$(Configuration)\</OutputPath>
    <Version>4.0.0</Version>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\FlipClock\am.png" />
    <None Remove="Resources\FlipClock\Background\flip_bg.png" />
    <None Remove="Resources\FlipClock\Background\flip_clock_divider.png" />
    <None Remove="Resources\FlipClock\Background\flip_clock_tab_down.png" />
    <None Remove="Resources\FlipClock\Background\flip_clock_tab_shadow.png" />
    <None Remove="Resources\FlipClock\Background\flip_clock_tab_up.png" />
    <None Remove="Resources\FlipClock\base_default.png" />
    <None Remove="Resources\FlipClock\Digits\0.png" />
    <None Remove="Resources\FlipClock\Digits\1.png" />
    <None Remove="Resources\FlipClock\Digits\2.png" />
    <None Remove="Resources\FlipClock\Digits\3.png" />
    <None Remove="Resources\FlipClock\Digits\4.png" />
    <None Remove="Resources\FlipClock\Digits\5.png" />
    <None Remove="Resources\FlipClock\Digits\6.png" />
    <None Remove="Resources\FlipClock\Digits\7.png" />
    <None Remove="Resources\FlipClock\Digits\8.png" />
    <None Remove="Resources\FlipClock\Digits\9.png" />
    <None Remove="Resources\FlipClock\modern_base_default.png" />
    <None Remove="Resources\FlipClock\modern_forecast_base.png" />
    <None Remove="Resources\FlipClock\pm.png" />
    <None Remove="Resources\FlipClock\SearchCancelIcon.png" />
    <None Remove="Resources\FlipClock\SearchIcon.png" />
    <None Remove="Resources\FlipClock\wide_base_default.png" />
    <None Remove="Resources\FlipClock\wide_forecast_base.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="5.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Home.Base\Home.Base.csproj" />
    <ProjectReference Include="..\Widgets\Clock\Clock.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\FlipClock\am.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\Background\flip_bg.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\Background\flip_clock_divider.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\Background\flip_clock_tab_down.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\Background\flip_clock_tab_shadow.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\Background\flip_clock_tab_up.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\base_default.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\Digits\0.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\Digits\1.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\Digits\2.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\Digits\3.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\Digits\4.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\Digits\5.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\Digits\6.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\Digits\7.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\Digits\8.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\Digits\9.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\modern_base_default.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\modern_forecast_base.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\pm.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\SearchCancelIcon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\SearchIcon.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\wide_base_default.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\FlipClock\wide_forecast_base.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
