<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <Copyright>© Stealth 2021</Copyright>
    <Authors>swups</Authors>
    <Version>1.2.0</Version>
    <Product>Foreca weather provider</Product>
  <OutputPath>..\..\..\bin\$(Configuration)\Extras\Weather\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Foreca.ext.xml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Home.Base\Home.Base.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\..\Weather.Base\Weather.Base.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>
</Project>
